#By Nova James Warner
adjective = input("Enter an adjective:")
noun = input("Enter a noun:")
verb = input("Enter a verb in past tense:")
adverb = input("Enter an adverb:")
place_bad = input("Enter a place you don't like:")
animal = input("Enter your favorite or a random animal:")
place_good = input("Enter a place you would like to visit:")
bad_thing = input("Enter something you don't like:")
good_thing = input("Enter something you enjoy:")
person = input("Enter someone's name:")
pet_name = input("Enter a name you would call your pet:")
complaint = input("Enter something you would say when you complain:")
print("Last night I had a " + adjective + " dream. I was chasing a " + noun + " and it " + verb + " away from me " + adverb + ". When I woke up, I realized today my mom was taking me to " + place_bad + ". This is going to be the worst day ever! Even worse than that time I had to eat some " + bad_thing + ". I wish I could just go to " + place_good + ". " + person + " won't let me though. At least at " + place_bad + " they will have " + good_thing + ". Before we leave, I have to take " + pet_name + ",my " + animal + ",on a walk. " + complaint + "!")