import turtle
#by Nova James Warner
SCREEN = turtle.Screen()
t = turtle.Turtle()
SCREEN.bgcolor("LightSeaGreen")
t.color("DarkOliveGreen")
t.shape("turtle")
t.pensize(5)
# Complete the following custom_shape function to define your own shape!
def custom_shape():
    t.fillcolor("Darkgreen")
    t.begin_fill()
    t.speed(7)
    points = [1,2]
    points.append(t.pos())
    points.append(t.pos())
    #making the shell
    t.forward(100)
    t.backward(180)
    t.left(90)
    t.forward(75)
    t.end_fill()
    t.begin_fill()
    t.backward(150)
    t.right(90)
    t.forward(180)
    t.left(90)
    t.forward(150)
    t.end_fill()
    t.begin_fill()
    t.left(90)
    t.forward(180)
    t.backward(90)
    t.left(90)
    t.forward(150)
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(70)
    t.left(90)
    t.end_fill()
    #making the head
    t.fillcolor("SaddleBrown")
    t.begin_fill()
    t.forward(30)
    t.left(80)
    t.right(180)
    t.circle(30)
    t.forward(15)
    t.right(90)
    t.forward(25)
    t.end_fill()
    t.right(-10)
    t.forward(181)
    t.backward(180)
    #making the legs
    t.fillcolor("SaddleBrown")
    t.penup()
    t.right(90)
    t.forward(80)
    t.left(90)
    t.forward(50)
    t.pendown()
    t.begin_fill()
    t.right(80)
    t.forward(25)
    t.right(10)
    t.forward(25)
    t.right(80)
    t.forward(15)
    t.right(80)
    t.forward(25)
    t.right(10)
    t.forward(25)
    t.penup()
    t.right(100)
    t.forward(110)
    t.right(80)
    t.pendown()
    t.forward(25)
    t.right(10)
    t.forward(25)
    t.right(80)
    t.forward(15)
    t.right(80)
    t.forward(25)
    t.right(10)
    t.forward(25)
    t.end_fill()
    #making the tail
    t.penup()
    t.left(90)
    t.backward(80)
    t.right(89)
    t.forward(55)
    t.pendown()
    t.begin_fill()
    t.right(85)
    t.forward(40)
    t.left(140)
    t.forward(51)
    t.left(125)
    t.end_fill()
    #making turtle
    t.penup()
    t.right(100)
    t.forward(150)
    t.right(90)
    t.forward(100)
    t.color("OrangeRed")
    t.write("TURTLE", font=("Courier", 32, "normal"))
    turtle.done()
    return points

SCREEN.register_shape('custom', custom_shape())
t.shape('custom')
